lib/simple_auth_web/router.ex
defmodule SimpleAuthWeb.Router do
  use SimpleAuthWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug SimpleAuth.CurrentUser
  end

  pipeline :auth do
    plug SimpleAuthWeb.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", SimpleAuthWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index

    resources "/users", UserController, only: [:show, :new, :create]

    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # scope "/", SimpleAuthWeb do
  #   pipe_through [:browser, :auth, :ensure_auth]
  #
  #   resources "/users", UserController, only: [:show]
  # end

  # Other scopes may use custom stacks.
  # scope "/api", SimpleAuthWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SimpleAuthWeb.Telemetry
    end
  end
end

lib/simple_auth/application.ex
defmodule SimpleAuth.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      SimpleAuth.Repo,
      # Start the Telemetry supervisor
      SimpleAuthWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: SimpleAuth.PubSub},
      # Start the Endpoint (http/https)
      SimpleAuthWeb.Endpoint
      # Start a worker by calling: SimpleAuth.Worker.start_link(arg)
      # {SimpleAuth.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: SimpleAuth.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    SimpleAuthWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/simple_auth/post.ex
defmodule SimpleAuth.Post do
  use Ecto.Schema
  import Ecto.Changeset

  @require_fields [:title]
  @optional_fields ~w(body)a


  schema "posts" do
    belongs_to :user, SimpleAuth.User
    field :body, :string
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(post, attrs) do
    post
    |> cast(attrs, [:title, :body])
    |> validate_required([:title, :body])
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @require_fields ++ @optional_fields)
    |> validate_required(@require_fields)
  end
end

lib/simple_auth/repo.ex
defmodule SimpleAuth.Repo do
  use Ecto.Repo,
    otp_app: :simple_auth,
    adapter: Ecto.Adapters.Postgres
end

lib/simple_auth/user.ex
defmodule SimpleAuth.User do
  use Ecto.Schema
  import Ecto.Changeset

  @require_fields [:email]
  @optional_fields ~w(name is_admin)a

  schema "users" do
    field :email, :string
    field :is_admin, :boolean, default: false
    field :name, :string
    field :password, :string, virtual: true
    field :password_hash, :string


    timestamps()
    has_many :posts, SimpleAuth.Post
  end

  @doc false
   def changeset(struct, params \\ %{}) do
     struct
     |> cast(params, @require_fields ++ @optional_fields)
     |> validate_required(@require_fields)
   end

   def registration_changeset(struct, params) do
     struct
     |> changeset(params)
     |> cast(params, [:password], [])
     |> validate_length(:password, min: 6, max: 100)
     |> hash_password
   end

   defp hash_password(changeset) do
     case changeset do
       %Ecto.Changeset{valid?: true, changes: %{password: password}} ->
          put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(password))
       _ ->
          changeset
     end
   end
end

lib/simple_auth_web/controllers/page_controller.ex
defmodule SimpleAuthWeb.PageController do
  use SimpleAuthWeb, :controller
  alias SimpleAuthWeb.Auth
  alias SimpleAuth.User
  alias SimpleAuthWeb.Guardian

  def index(conn, _params) do
      render(conn, "index.html")
    end

  #   def login(conn, %{"user" => %{"username" => username, "password" => password}}) do
  #     User.authenticate_user(username, password)
  #     |> login_reply(conn)
  #   end
  #
  #   defp login_reply({:error, error}, conn) do
  #   conn
  #     |> put_flash(:error, error)
  #     |> redirect(to: "/")
  #   end
  #
  #   defp login_reply({:ok, user}, conn) do
  #     conn
  #     |> put_flash(:success, "Welcome back!")
  #     |> Guardian.Plug.sign_in(user)
  #     |> redirect(to: "/")
  #   end
  #
  #   def logout(conn, _) do
  #     conn
  #     |> Guardian.Plug.sign_out()
  #     |> redirect(to: Routes.page_path(conn, :login))
  #   end
  #
  #   def secret(conn, _params) do
  #     render(conn, "secret.html")
  #   end
  end

lib/simple_auth_web/controllers/session_controller.ex
defmodule SimpleAuthWeb.SessionController do
  use SimpleAuthWeb, :controller
  alias SimpleAuth.User
  alias SimpleAuth.Repo

  plug :scrub_params, "session" when action in [:create]

  def new(conn, _) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => %{"email" => email, "password" => password}}) do
    user = Repo.get_by(User, email: email)

    case user do
      nil ->
        conn
        |> put_flash(:error, "Does not exist!")
        |> render("new.html")

      _ ->
        if Comeonin.Bcrypt.checkpw(password, user.password_hash) do
          conn
          |> SimpleAuthWeb.Guardian.Plug.sign_in(user)
          |> put_flash(:info, "You're in!")
          |> redirect(to: Routes.user_path(conn, :show, user))

        else
          conn
          |> put_flash(:error, "Incorrect Password")
          |> render("new.html")
        end
    end
  end
      #
      # defp login_reply(conn, user) do
      #   conn
      #   |> put_flash(:success, "Welcome back!")
      #   |> redirect(to: Routes.user_path(conn, :show, user))
      # end
      #

  def delete(conn, _) do
  end

end

lib/simple_auth_web/controllers/user_controller.ex
defmodule SimpleAuthWeb.UserController do
  use SimpleAuthWeb, :controller
  alias SimpleAuth.User
  alias SimpleAuth.Repo


  def show(conn, _) do
    user = SimpleAuthWeb.Guardian.Plug.current_resource(conn)
    render(conn, "show.html", user: user)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  plug :scrub_params, "user" when action in [:create]

  def create(conn, %{"user" => user_params}) do
    changeset = %User{} |> User.registration_changeset(user_params)

    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: Routes.user_path(conn, :show, user))

       {:error, changeset} ->
         render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/simple_auth_web/views/error_view.ex
defmodule SimpleAuthWeb.ErrorView do
  use SimpleAuthWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/simple_auth_web/views/layout_view.ex
defmodule SimpleAuthWeb.LayoutView do
  use SimpleAuthWeb, :view
end

lib/simple_auth_web/views/page_view.ex
defmodule SimpleAuthWeb.PageView do
  use SimpleAuthWeb, :view
end

lib/simple_auth_web/views/session_view.ex
defmodule SimpleAuthWeb.SessionView do
  use SimpleAuthWeb, :view
end

lib/simple_auth_web/views/user_view.ex
defmodule SimpleAuthWeb.UserView do
  use SimpleAuthWeb, :view
end

lib/simple_auth_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>SimpleAuth · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
            <li><%= link "Sign in", to: Routes.session_path(@conn, :new) %></li>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/simple_auth_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace of mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.5/CHANGELOG.md">v1.5 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
    </ul>
  </article>
</section>

lib/simple_auth_web/templates/session/new.html.eex
<h1>Sign in</h1>
<%= form_for @conn, Routes.session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <%= text_input f, :email, placeholder: "Email", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
<%= submit "Sign in", class: "btn btn-primary" %>
<% end %>

lib/simple_auth_web/templates/user/new.html.eex
<h1>User Registration</h1>
<%= form_for @changeset, Routes.user_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>There are some errors</p>
    </div>
  <% end %>
  <div class="form-group">
    <%= text_input f, :email, placeholder: "Email",
        class: "form-control" %>
    <%= error_tag f, :email %>
  </div>
  <div class="form-group">
    <%= text_input f, :name, placeholder: "Name",
        class: "form-control" %>
    <%= error_tag f, :name %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password",
        class: "form-control" %>
    <%= error_tag f, :password %>
  </div>
  <%= submit "Create User", class: "btn btn-primary" %>
<% end %>

lib/simple_auth_web/templates/user/show.html.eex
<h2><%= @user.name %></h2>
<p><%= @user.email %></p>